// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raposa.Lanches.DataBase;

namespace Raposa.Lanches.DataBase.Migrations
{
    [DbContext(typeof(RaposaLanchesContext))]
    [Migration("20201015170837_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Raposa.Lanches.DataBase.Ingrediente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Hamburguer",
                            Valor = 4.5m
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Pão",
                            Valor = 4.75m
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Queijo",
                            Valor = 4m
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Tomate",
                            Valor = 1m
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Alface",
                            Valor = 1m
                        },
                        new
                        {
                            ID = 6,
                            Nome = "Bacon",
                            Valor = 4m
                        },
                        new
                        {
                            ID = 7,
                            Nome = "Ovo",
                            Valor = 2m
                        },
                        new
                        {
                            ID = 8,
                            Nome = "Cebola Roxa",
                            Valor = 1m
                        },
                        new
                        {
                            ID = 9,
                            Nome = "Pão australiano",
                            Valor = 5m
                        });
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.Lanche", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lanches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "x-salada"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "x-salada bacon"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "x-egg"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "duplo bacon"
                        });
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.LancheIngrediente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("LancheId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("LancheId");

                    b.ToTable("LancheIngredientes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IngredienteId = 1,
                            LancheId = 1
                        },
                        new
                        {
                            ID = 2,
                            IngredienteId = 2,
                            LancheId = 1
                        },
                        new
                        {
                            ID = 3,
                            IngredienteId = 4,
                            LancheId = 1
                        },
                        new
                        {
                            ID = 4,
                            IngredienteId = 5,
                            LancheId = 1
                        },
                        new
                        {
                            ID = 5,
                            IngredienteId = 1,
                            LancheId = 2
                        },
                        new
                        {
                            ID = 6,
                            IngredienteId = 2,
                            LancheId = 2
                        },
                        new
                        {
                            ID = 7,
                            IngredienteId = 4,
                            LancheId = 2
                        },
                        new
                        {
                            ID = 8,
                            IngredienteId = 5,
                            LancheId = 2
                        },
                        new
                        {
                            ID = 9,
                            IngredienteId = 6,
                            LancheId = 2
                        },
                        new
                        {
                            ID = 10,
                            IngredienteId = 1,
                            LancheId = 3
                        },
                        new
                        {
                            ID = 11,
                            IngredienteId = 2,
                            LancheId = 3
                        },
                        new
                        {
                            ID = 12,
                            IngredienteId = 7,
                            LancheId = 3
                        },
                        new
                        {
                            ID = 13,
                            IngredienteId = 1,
                            LancheId = 4
                        },
                        new
                        {
                            ID = 14,
                            IngredienteId = 1,
                            LancheId = 4
                        },
                        new
                        {
                            ID = 15,
                            IngredienteId = 2,
                            LancheId = 4
                        },
                        new
                        {
                            ID = 16,
                            IngredienteId = 3,
                            LancheId = 4
                        },
                        new
                        {
                            ID = 17,
                            IngredienteId = 6,
                            LancheId = 4
                        });
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.LancheIngrediente", b =>
                {
                    b.HasOne("Raposa.Lanches.DataBase.Ingrediente", "Ingrediente")
                        .WithMany("LancheIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raposa.Lanches.DataBase.Lanche", "Lanche")
                        .WithMany("LancheIngredientes")
                        .HasForeignKey("LancheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
