// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raposa.Lanches.DataBase;

namespace Raposa.Lanches.DataBase.Migrations
{
    [DbContext(typeof(RaposaLanchesContext))]
    partial class RaposaLanchesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Raposa.Lanches.DataBase.Ingrediente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.Lanche", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lanches");
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.LancheIngrediente", b =>
                {
                    b.Property<int>("LancheId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.HasKey("LancheId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("LancheIngredientes");
                });

            modelBuilder.Entity("Raposa.Lanches.DataBase.LancheIngrediente", b =>
                {
                    b.HasOne("Raposa.Lanches.DataBase.Ingrediente", "Ingrediente")
                        .WithMany("LancheIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raposa.Lanches.DataBase.Lanche", "Lanche")
                        .WithMany("LancheIngredientes")
                        .HasForeignKey("LancheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
